[metadata]
name = beeixon
version = 0.0.1
author = BEE Group - CIMNE
author_email = beegroup@cimne.upc.edu
description = API client to access data from Ixon Cloud (https://developer.ixon.cloud)
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/BeeGroup-cimne/beeixon
project_urls =
    Bug Tracker = https://github.com/BeeGroup-cimne/beeixon/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: EUPL
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8
install_requires =
    requests
    pandas
    # TODO: bump to the commit that includes beerest.py once it's pushed to beelib
    beelib @ git+https://github.com/BeeGroup-cimne/beelib@b1b3310020ff66dbfbf53ffedca8030f4f94ecf9

[options.packages.find]
where = src
